export default dataItems = [
    { src: require('../../assets/data/aosomi.jpg'), colorStyle: '#FFFFFF' , description: 'Áo sơ mi nam'}, 
    { src: require('../../assets/data/camera.jpg'), colorStyle: '#FFFFFF', description: 'Camera giám sát'},
    { src: require('../../assets/data/chuot.jpg'), colorStyle: '#FFFFFF', description: 'Chuột cao cấp' }, 
    { src: require('../../assets/data/dongho.jpg'), colorStyle: '#FFFFFF', description: 'Đồng hồ nam' },
    { src: require('../../assets/data/samsung.jpg'), colorStyle: '#FFFFFF', description: 'Điện thoại samsung' }, 
    { src: require('../../assets/data/tainghe.png'), colorStyle: '#FFFFFF', description: 'Tai nghe cao cấp' },
    { src: require('../../assets/data/aosomi.jpg'), colorStyle: '#FFFFFF' , description: 'Áo sơ mi nam'}, 
    { src: require('../../assets/data/camera.jpg'), colorStyle: '#FFFFFF', description: 'Camera giám sát'},
    { src: require('../../assets/data/chuot.jpg'), colorStyle: '#FFFFFF', description: 'Chuột cao cấp' }, 
    { src: require('../../assets/data/dongho.jpg'), colorStyle: '#FFFFFF', description: 'Đồng hồ nam' },
    { src: require('../../assets/data/samsung.jpg'), colorStyle: '#FFFFFF', description: 'Điện thoại samsung' }, 
    { src: require('../../assets/data/tainghe.png'), colorStyle: '#FFFFFF', description: 'Tai nghe cao cấp' },
    { src: require('../../assets/data/aosomi.jpg'), colorStyle: '#FFFFFF' , description: 'Áo sơ mi nam'}, 
    { src: require('../../assets/data/camera.jpg'), colorStyle: '#FFFFFF', description: 'Camera giám sát'},
    { src: require('../../assets/data/chuot.jpg'), colorStyle: '#FFFFFF', description: 'Chuột cao cấp' }, 
    { src: require('../../assets/data/dongho.jpg'), colorStyle: '#FFFFFF', description: 'Đồng hồ nam' },
    { src: require('../../assets/data/samsung.jpg'), colorStyle: '#FFFFFF', description: 'Điện thoại samsung' }, 
    { src: require('../../assets/data/tainghe.png'), colorStyle: '#FFFFFF', description: 'Tai nghe cao cấp' },
    { src: require('../../assets/data/aosomi.jpg'), colorStyle: '#FFFFFF' , description: 'Áo sơ mi nam'}, 
    { src: require('../../assets/data/camera.jpg'), colorStyle: '#FFFFFF', description: 'Camera giám sát'},
    { src: require('../../assets/data/chuot.jpg'), colorStyle: '#FFFFFF', description: 'Chuột cao cấp' }, 
    { src: require('../../assets/data/dongho.jpg'), colorStyle: '#FFFFFF', description: 'Đồng hồ nam' },
    { src: require('../../assets/data/samsung.jpg'), colorStyle: '#FFFFFF', description: 'Điện thoại samsung' }, 
    { src: require('../../assets/data/tainghe.png'), colorStyle: '#FFFFFF', description: 'Tai nghe cao cấp' },
    { src: require('../../assets/data/aosomi.jpg'), colorStyle: '#FFFFFF' , description: 'Áo sơ mi nam'}, 
    { src: require('../../assets/data/camera.jpg'), colorStyle: '#FFFFFF', description: 'Camera giám sát'},
    { src: require('../../assets/data/chuot.jpg'), colorStyle: '#FFFFFF', description: 'Chuột cao cấp' }, 
    { src: require('../../assets/data/dongho.jpg'), colorStyle: '#FFFFFF', description: 'Đồng hồ nam' },
    { src: require('../../assets/data/samsung.jpg'), colorStyle: '#FFFFFF', description: 'Điện thoại samsung' }, 
    { src: require('../../assets/data/tainghe.png'), colorStyle: '#FFFFFF', description: 'Tai nghe cao cấp' },
    { src: require('../../assets/data/aosomi.jpg'), colorStyle: '#FFFFFF' , description: 'Áo sơ mi nam'}, 
    { src: require('../../assets/data/camera.jpg'), colorStyle: '#FFFFFF', description: 'Camera giám sát'},
    { src: require('../../assets/data/chuot.jpg'), colorStyle: '#FFFFFF', description: 'Chuột cao cấp' }, 
    { src: require('../../assets/data/dongho.jpg'), colorStyle: '#FFFFFF', description: 'Đồng hồ nam' },
    { src: require('../../assets/data/samsung.jpg'), colorStyle: '#FFFFFF', description: 'Điện thoại samsung' }, 
    { src: require('../../assets/data/tainghe.png'), colorStyle: '#FFFFFF', description: 'Tai nghe cao cấp' },
    { src: require('../../assets/data/tainghe.png'), colorStyle: '#FFFFFF', description: 'Tai nghe cao cấp' },
    { src: require('../../assets/data/aosomi.jpg'), colorStyle: '#FFFFFF' , description: 'Áo sơ mi nam'}, 
    { src: require('../../assets/data/camera.jpg'), colorStyle: '#FFFFFF', description: 'Camera giám sát'},
    { src: require('../../assets/data/chuot.jpg'), colorStyle: '#FFFFFF', description: 'Chuột cao cấp' }, 
    { src: require('../../assets/data/dongho.jpg'), colorStyle: '#FFFFFF', description: 'Đồng hồ nam' },
    { src: require('../../assets/data/samsung.jpg'), colorStyle: '#FFFFFF', description: 'Điện thoại samsung' }, 
    { src: require('../../assets/data/tainghe.png'), colorStyle: '#FFFFFF', description: 'Tai nghe cao cấp' },
    { src: require('../../assets/data/aosomi.jpg'), colorStyle: '#FFFFFF' , description: 'Áo sơ mi nam'}, 
    { src: require('../../assets/data/camera.jpg'), colorStyle: '#FFFFFF', description: 'Camera giám sát'},
    { src: require('../../assets/data/chuot.jpg'), colorStyle: '#FFFFFF', description: 'Chuột cao cấp' }, 
    { src: require('../../assets/data/dongho.jpg'), colorStyle: '#FFFFFF', description: 'Đồng hồ nam' },
    { src: require('../../assets/data/samsung.jpg'), colorStyle: '#FFFFFF', description: 'Điện thoại samsung' }, 
    { src: require('../../assets/data/tainghe.png'), colorStyle: '#FFFFFF', description: 'Tai nghe cao cấp' },
    
]